spring:
  kafka:
    bootstrap-servers: localhost:29092
    streams:
      application-id: messaging-task
      bootstrap-servers: localhost:29092
custom:
  kafka:
    topic1-1: task-1-1
    topic1-2: task-1-2
    topic1-3: task-1-3
    topic1-4: task-1-4
server:
  port: 8081